package com.rodrigo7prado.sisGestEduc.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto;
import com.rodrigo7prado.sisGestEduc.entities.AlunoPeriodoCurricular;

@Repository
public interface AlunoPeriodoCurricularRepository extends JpaRepository<AlunoPeriodoCurricular, Long> {
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' "
			+ "AND v.id.ano LIKE 'Ano Letivo: 2017%' "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterNull();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' "
			+ "OR v.id.ano LIKE 'Ano Letivo: 2017%' "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterTodos();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' "
					+ ""
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterUltimosPeriodosLetivos();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterConcluintes();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
					+ "AND a.dataNasc IS NULL "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterPendDataNasc();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
					+ "AND a.nacionalidade IS NULL "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterPendNacionalidade();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
					+ "AND a.naturalidade IS NULL "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterPendNaturalidade();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
					+ "AND a.rg IS NULL "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterPendRg();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
					+ "AND a.nomePai IS NULL "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterPendNomePai();
	
	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a"
			+ ", v.id.ano"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.id.turma"
			+ ", v.nomeCompl"
			+ ", a.sexo"
			+ ", a.dataNasc"
			+ ", a.nomePai"
			+ ", a.nomeMae"
			+ ", a.nacionalidade"
			+ ", a.naturalidade"
			+ ", a.naturalidadeUF"
			+ ", a.rg"
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"
			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
					+ "AND a.nomeMae IS NULL "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterPendNomeMae();

	@Query("SELECT DISTINCT new com.rodrigo7prado.sisGestEduc.dto.AlunoPeriodoCurricularDto(" + "v,a" + ", v.id.ano"
			+ ", v.id.turma" + ", v.id.turma" + ", v.id.turma" + ", v.nomeCompl" + ", a.sexo" + ", a.dataNasc"
			+ ", a.nomePai" + ", a.nomeMae" + ", a.nacionalidade" 
			+ ", a.naturalidade" 
			+ ", a.naturalidadeUF"
			+ ", a.rg" 
			+ ", a.rgEmissor"
			+ ", a.rgEmissorUf"
			+ ", v.id.aluno"
			+ ", v.id.situacaoFinal"

			+ ") " + "FROM VwAlunoPeriodoCurricular v " + "LEFT JOIN AlunoExternal a " + "ON v.id.aluno = a.id "
			+ "WHERE " + "v.id.ano LIKE 'Ano Letivo: 2018%' " + "AND v.id.situacaoFinal = 'Aprovado' "
			+ "ORDER BY v.id.turma, v.nomeCompl")
	List<AlunoPeriodoCurricularDto> findFilterQuaisquerPendencias();
}
